apiVersion: v1
kind: Pod
metadata:
  name: tensorflow-benchmarks-gpu
spec:
  containers:
  - image: nvcr.io/nvidia/tensorflow:21.02-tf1-py3
    name: cudnn
    command: ["/bin/sh","-c"]
    args: ["git clone https://github.com/tensorflow/benchmarks.git;cd benchmarks/scripts/tf_cnn_benchmarks;python3 tf_cnn_benchmarks.py --num_gpus=1 --data_format=NHWC --batch_size=32 --model=alexnet --variable_update=parameter_server"]
    env:
      - name: http_proxy
        value: <YOUR IP>
      - name: https_proxy
        value: <YOUR IP>
    resources:
      limits:
        cpu: "2000m"
        memory: "8Gi"
        nvidia.com/gpu: 1
      requests:
        cpu: "2000m"
        memory: "8Gi"
        nvidia.com/gpu: 1
  tolerations:
  - key: "nodetype"
    operator: "Equal"
    value: "gpu"
    effect: "NoSchedule"
  restartPolicy: Never
