# This manifest for HPE Eameral Runtime
---
apiVersion: v1
kind: Pod
metadata:
  name: apls
  labels:
    app: apls
spec:
  restartPolicy: Always
  volumes:
  - name: data
    persistentVolumeClaim:
      claimName: apls-data
  containers:
  - name: apls
    image: <swarm-learning/apls:tag>
    volumeMounts:
    - name: data
      mountPath: /opt/autopass/AutopassLicenseServer/data
    ports:
    - containerPort: 5814
    resources:
      requests:
        memory: 2Gi
        cpu: 1000m
      limits:
        memory: 2Gi
        cpu: 1000m
    env:
    - name: SWARM_LICENSE_AUTOPASSJ_SERVER_PRIMARY_IP
      valueFrom:
        fieldRef:
          fieldPath: status.podIP
    - name: SWARM_LICENSE_AUTOPASSJ_SERVER_PRIMARY_PORT
      value: "5814"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: apls-data
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: datafabric01
---
apiVersion: v1
kind: Service
metadata:
  name: apls
spec:
  selector:
    app: apls
  ports:
  - port: 5814
  type: NodePort