---
apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: sl-node02
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sl-node02
rules:
- apiGroups: ["*"]
  resources: ["pods"]
  verbs: ["get", "list"]
- apiGroups: ["*"]
  resources: ["pods/exec"]
  verbs: ["create"]
- apiGroups: ["*"]
  resources: ["secrets"]
  verbs: ["get", "create", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sl-node02
subjects:
  - kind: ServiceAccount
    name: sl-node02
roleRef:
  kind: Role
  apiGroup: rbac.authorization.k8s.io
  name: sl-node02
---
# This is dummy token
# Updated by spire-token-generator init container
# Name should be unique on each network node
apiVersion: v1
kind: Secret
metadata:
  creationTimestamp: null
  name: sl-node02
type: Opaque
data:
  token: ZHVtbXkK
---
apiVersion: v1
kind: Service
metadata:
  name: sl-node02
spec:
  selector:
    app: sl-node02
  ports:
  - name: fs
    port: 30305
  - name: api
    port: 30304
  - name: p2p
    port: 30303
  type: ClusterIP
---
apiVersion: v1
kind: Pod
metadata:
  name: sl-node02
  labels:
     app: sl-node02
     #This is for HPE Ezmeral Rutime shared volumes
     #Mount point is /bd-fs-mnt/TenantShare
     hpecp.hpe.com/fsmount: swarm
spec:
  terminationGracePeriodSeconds: 60
  restartPolicy: Never
  serviceAccountName: sl-node02
  initContainers:
  - name: spire-token-generator
    image: docker.io/fideltak/spire-token-generator:1.20.11_v0.4
    resources:
      requests:
        memory: 0.2Gi
        cpu: 200m
      limits:
        memory: 0.2Gi
        cpu: 200m
    env:
    - name: SPIRE_POD_LABEL
      value: "app=spire-server"
    - name: SPIRE_SPIFFE_ID
      value: "spiffe://swarm.learning/swarm/sl-agent"
    - name: SPIRE_TOKEN_SECRET_NAME
      value: "sl-node02"
  containers:
  - name: sl-node02
    image: <your-repo>/sl-tf:0.3.0
    securityContext:
      runAsUser: 0
    resources:
      requests:
        memory: 8Gi
        cpu: 2000m
      limits:
        memory: 8Gi
        cpu: 2000m
    ports:
    - containerPort: 30303
    - containerPort: 30304
    - containerPort: 30305
    args:
    - "-joinToken"
    - "$(SPIRE_JOIN_TOKEN)"
    - "-serverAddress"
    - "$(SPIRE_SERVER_IP)"
    - "-serverPort"
    - "$(SPIRE_SERVER_PORT)"
    - "-insecureBootstrap"
    - "true"
    - "-logLevel"
    - "debug"
#    - "--data-dir"
#    - "$(MODEL_DATA_DIR)"
#    - "--model-dir"
#    - "$(MODEL_DIR)"
#    - "--model-program"
#    - "$(MODEL_PROGRAM_NAME)"
    env:
    - name: SPIRE_SERVER_IP
      value: "spire-server"
    - name: SPIRE_SERVER_PORT
      value: "8081"
    - name: SPIRE_JOIN_TOKEN
      valueFrom:
        secretKeyRef:
          name: sl-node02
          key: token
    - name: SWARM_LICENSE_AUTOPASSJ_SERVER_PRIMARY_IP
      value: "apls"
    - name: SWARM_LICENSE_AUTOPASSJ_SERVER_PRIMARY_PORT
      value: "5814"
      # The IP address or DNS name of the host system on which this
      # Swarm Network node will be created.
    - name: THIS_NODE_IP
      value: "sl-node02"

      # The IP address or DNS name of the host system on which the
      # Sentinel Swarm Network node is running. If this parameter
      # is not specified, this Swarm Network node will make itself
      # the sentinel
    - name: SENTINEL_NODE_IP
      value: "network-node01"

      # Host port for this Swarm Network node's API Server.
    - name: API_SERVER_PORT
      value: "30304"

      # Host port for this Swarm Network node's File Server
    - name: ML_FS_PORT
      value: "30305"

    - name: MLCMD
      value: "run /bd-fs-mnt/TenantShare/swarm/test/sl-node02/model/mnist_tf.py"

    - name: DATA_DIR
      value: "/bd-fs-mnt/TenantShare/swarm/test/sl-node02/data"

    - name: MAX_EPOCHS
      value: "5"

    - name: MODEL_DIR
      value: "/bd-fs-mnt/TenantShare/swarm/test/sl-node02/"

#    - name: SINGLE_NODE_BLOCKCHAIN
#      value: "TRUE"

#    - name: NVIDIA_VISIBLE_DEVICES
#      value: "0"