---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc01
  namespace: hpe-storage
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: hpe-nimble-block